// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGIBj97pvnGM5UUr8C9ADxkkY_8IDZmZE',
    appId: '1:588251230005:web:d9cfa70ef0a7814061a67c',
    messagingSenderId: '588251230005',
    projectId: 'tinder-e21ab',
    authDomain: 'tinder-e21ab.firebaseapp.com',
    storageBucket: 'tinder-e21ab.appspot.com',
    measurementId: 'G-BVBFYF1Y2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkBwkeBV0jysOvF4r6a83eILJdIvqZ4dI',
    appId: '1:588251230005:android:8df21d36255677fb61a67c',
    messagingSenderId: '588251230005',
    projectId: 'tinder-e21ab',
    storageBucket: 'tinder-e21ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE-h9m-D11lXtlgMP2GarhraPKWHRj8Fw',
    appId: '1:588251230005:ios:73b4e22043a93c3761a67c',
    messagingSenderId: '588251230005',
    projectId: 'tinder-e21ab',
    storageBucket: 'tinder-e21ab.appspot.com',
    iosBundleId: 'com.example.tinderCloneFlutterGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE-h9m-D11lXtlgMP2GarhraPKWHRj8Fw',
    appId: '1:588251230005:ios:73b4e22043a93c3761a67c',
    messagingSenderId: '588251230005',
    projectId: 'tinder-e21ab',
    storageBucket: 'tinder-e21ab.appspot.com',
    iosBundleId: 'com.example.tinderCloneFlutterGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGIBj97pvnGM5UUr8C9ADxkkY_8IDZmZE',
    appId: '1:588251230005:web:8c64c86610ba435761a67c',
    messagingSenderId: '588251230005',
    projectId: 'tinder-e21ab',
    authDomain: 'tinder-e21ab.firebaseapp.com',
    storageBucket: 'tinder-e21ab.appspot.com',
    measurementId: 'G-QMPEVJ619L',
  );
}
